# Application name

spring.application.name=JamiiX

# Database properties

spring.datasource.url=jdbc:postgresql://ep-wild-rain-asmjrufc-pooler.c-4.eu-central-1.aws.neon.tech/jamiidb
spring.datasource.username=system
spring.datasource.password=npg_1BcFnQJqwC5T
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Connection pooling settings

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# File upload sizes

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Spring Session settings

spring.session.jdbc.initialize-schema=always
server.servlet.session.timeout=5m

# Server port

server.port=${PORT:8080}
# Logging

logging.level.root=INFO
logging.level.com.jamii=INFO

# Flyway Migrations

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:migration
# Cors configurations
app.cors.allowed-origins=https://jamiix.netlify.app,http://localhost:3000
